### ISSUE TITLE
Questions about positioning sounds

### ISSUE THREAD

**Issue by AcrylicShrimp** [mbillingr/ambisonic#15]
Hello!

I'm trying to adopt this for my game engine, and it's hard to understand how the positioning is working.

First of all, I cannot hear anything when a sound source is at `0, 0, 0`. But I can hear when it is at `0, 0.0001, 0` and sort of. Why I cannot hear sounds of origin? Is there documentations about this?

Second, which dimension the X, Y and Z represents? Maybe, X for left-to-right, Y for down-to-up, Z for back-to-front?

I'm sorry for bothering you, thanks!

**Comment by mbillingr** [comment]
Hi there!

If I didn't want to be bothered, I should write better documentation :smile:.

- No sound at `[0, 0, 0]`: This is expected, but not documented as far I know my former self... If I remember correctly, the reasoning behind that issue is that the engine needs to compute the direction the sound is coming from. This direction is undefined at the origin, resulting in `nan`s and no sound. I wanted to avoid branching in the rendering loop and left it at that. The physical meaning of a sound originating exactly at the listener's position is not clear to me, but it should probably sound as if it were coming from all directions equally. In this case you can use [`play_omni()`](https://docs.rs/ambisonic/latest/ambisonic/struct.Ambisonic.html#method.play_omni) to play the sound.

- Ambisonic does not make hard assumptions about your coordinate system. The default [`StereoConfig`](https://docs.rs/ambisonic/latest/ambisonic/struct.StereoConfig.html) is `-X` left, `X` right, `Y` front, `Z` up (again, undocumented... sorry). If you're used to the OpenGL coordinate system this may seem weird, but those directions are easy to change: 
  ```rust
  let mut render_config = StereoConfig::default();
  render_config.set_left_direction([-1.0, 0.0, 1.0]);  // point left microphone into -x/z direction
  render_config.set_right_direction([1.0, 0.0, 1.0]);  // point right microphone into x/z direction
  ```

**Comment by AcrylicShrimp** [comment]
Kind and quick response, thank you! Now I can understand how it's working. :)

**Comment by mbillingr** [comment]
You're welcome. Don't hesitate to reach out if you run into further issues.
